pub struct ParameterInfo {
    pub allow_plural: bool,
    pub allow_gender: bool,
}

#[derive(Debug, PartialEq, Copy, Clone)]
pub enum Occurence {
    ANY,     //< Command can be added or removed in translation without restriction.
    NONZERO, //< Command must appear in translation if and only if it is present in the base, but the amount may differ.
    EXACT,   //< Command must match exactly with base.
}

#[derive(PartialEq, Copy, Clone)]
pub enum Dialect {
    NEWGRF,
    GAMESCRIPT,
    OPENTTD,
}

impl From<&str> for Dialect {
    fn from(src: &str) -> Self {
        match src {
            "newgrf" => Dialect::NEWGRF,
            "game-script" => Dialect::GAMESCRIPT,
            "openttd" => Dialect::OPENTTD,
            _ => panic!(),
        }
    }
}

impl Into<String> for Dialect {
    fn into(self) -> String {
        match self {
            Dialect::NEWGRF => String::from("newgrf"),
            Dialect::GAMESCRIPT => String::from("game-script"),
            Dialect::OPENTTD => String::from("openttd"),
        }
    }
}

pub struct CommandInfo<'a> {
    pub name: &'a str,
    pub norm_name: Option<&'a str>,
    pub dialects: &'a [Dialect],
    pub occurence: Occurence,
    pub front_only: bool,
    pub allow_case: bool,
    pub def_plural_subindex: Option<usize>,
    pub parameters: &'a [ParameterInfo],
}

impl<'a> CommandInfo<'a> {
    pub fn get_norm_name(&self) -> &'a str {
        self.norm_name.unwrap_or(self.name)
    }
}

const P__: ParameterInfo = ParameterInfo {
    allow_plural: false,
    allow_gender: false,
};
const PP_: ParameterInfo = ParameterInfo {
    allow_plural: true,
    allow_gender: false,
};
const P_G: ParameterInfo = ParameterInfo {
    allow_plural: false,
    allow_gender: true,
};
const PPG: ParameterInfo = ParameterInfo {
    allow_plural: true,
    allow_gender: true,
};

const DN__: &'static [Dialect] = &[Dialect::NEWGRF];
const DNGO: &'static [Dialect] = &[Dialect::NEWGRF, Dialect::GAMESCRIPT, Dialect::OPENTTD];
const D_GO: &'static [Dialect] = &[Dialect::GAMESCRIPT, Dialect::OPENTTD];
const D__O: &'static [Dialect] = &[Dialect::OPENTTD];

pub const COMMANDS: &'static [CommandInfo] = &[
    // names for unicode characters, freely usable by translators
    CommandInfo {
        name: "NBSP",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "{",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    // these are still missing from NML: D_GO
    CommandInfo {
        name: "LRM",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "RLM",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "LRE",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "RLE",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "LRO",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "RLO",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "PDF",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    // special characters which are supposed to match between base and translations
    CommandInfo {
        name: "",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "COPYRIGHT",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "TRAIN",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "LORRY",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "BUS",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "PLANE",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "SHIP",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    // Some string parameters are only allowed in the OpenTTD project.
    // While they technically also work in Game Scripts, disencourage the usage.
    // This also includes the "sprite" characters.
    CommandInfo {
        name: "REV",
        norm_name: None,
        dialects: D__O,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "UP_ARROW",
        norm_name: None,
        dialects: D__O,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "SMALL_UP_ARROW",
        norm_name: None,
        dialects: D__O,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "SMALL_DOWN_ARROW",
        norm_name: None,
        dialects: D__O,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "DOWN_ARROW",
        norm_name: None,
        dialects: D__O,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "CHECKMARK",
        norm_name: None,
        dialects: D__O,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "CROSS",
        norm_name: None,
        dialects: D__O,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    // left/right arrows are Occurence::ANY due to LTR/RTL languages
    CommandInfo {
        name: "RIGHT_ARROW",
        norm_name: None,
        dialects: D__O,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "SMALL_LEFT_ARROW",
        norm_name: None,
        dialects: D__O,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "SMALL_RIGHT_ARROW",
        norm_name: None,
        dialects: D__O,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "STATION_FEATURES",
        norm_name: None,
        dialects: D__O,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P__],
    },
    // font sizes must be at the front: OpenTTD does not support text with mixed line height
    CommandInfo {
        name: "NORMAL_FONT",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: true,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "TINY_FONT",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: true,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "BIG_FONT",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: true,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "MONO_FONT",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: true,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    // colour codes can be needed multiple times, when reordering text in translations
    CommandInfo {
        name: "BLUE",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "SILVER",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "GOLD",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "RED",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "PURPLE",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "LTBROWN",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "ORANGE",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "GREEN",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "YELLOW",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "DKGREEN",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "CREAM",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "BROWN",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "WHITE",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "LTBLUE",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "GRAY",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "DKBLUE",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "BLACK",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::NONZERO,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    // TODO check that push and pop are balanced
    CommandInfo {
        name: "PUSH_COLOUR",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "POP_COLOUR",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::ANY,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[],
    },
    CommandInfo {
        name: "COLOUR",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P__],
    },
    CommandInfo {
        name: "POP_WORD",
        norm_name: None,
        dialects: DN__,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P__],
    },
    // substrings
    CommandInfo {
        name: "STRING",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
    CommandInfo {
        name: "RAW_STRING",
        norm_name: Some("STRING"),
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
    CommandInfo {
        name: "STRING1",
        norm_name: Some("STRING"),
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P_G, PPG],
    },
    CommandInfo {
        name: "STRING2",
        norm_name: Some("STRING"),
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P_G, PPG, PPG],
    },
    CommandInfo {
        name: "STRING3",
        norm_name: Some("STRING"),
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P_G, PPG, PPG, PPG],
    },
    CommandInfo {
        name: "STRING4",
        norm_name: Some("STRING"),
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P_G, PPG, PPG, PPG, PPG],
    },
    CommandInfo {
        name: "STRING5",
        norm_name: Some("STRING"),
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P_G, PPG, PPG, PPG, PPG, PPG],
    },
    CommandInfo {
        name: "STRING6",
        norm_name: Some("STRING"),
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P_G, PPG, PPG, PPG, PPG, PPG, PPG],
    },
    CommandInfo {
        name: "STRING7",
        norm_name: Some("STRING"),
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P_G, PPG, PPG, PPG, PPG, PPG, PPG, PPG],
    },
    // simple numbers
    CommandInfo {
        name: "COMMA",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "SIGNED_WORD",
        norm_name: None,
        dialects: DN__,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "UNSIGNED_WORD",
        norm_name: None,
        dialects: DN__,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "HEX",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "NUM",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    // formatted numbers
    CommandInfo {
        name: "ZEROFILL_NUM",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_, P__],
    },
    CommandInfo {
        name: "DECIMAL",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_, P__],
    },
    // numbers with unit
    CommandInfo {
        name: "BYTES",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "HEIGHT",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "CURRENCY",
        norm_name: None,
        dialects: DN__,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "CURRENCY_LONG",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "CURRENCY_SHORT",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "VELOCITY",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "VOLUME",
        norm_name: None,
        dialects: DN__,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "VOLUME_LONG",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "VOLUME_SHORT",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "FORCE",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "POWER",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "POWER_TO_WEIGHT",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "WEIGHT",
        norm_name: None,
        dialects: DN__,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "WEIGHT_LONG",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "WEIGHT_SHORT",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PP_],
    },
    CommandInfo {
        name: "UNITS_DAYS_OR_SECONDS",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PPG],
    },
    CommandInfo {
        name: "UNITS_MONTHS_OR_MINUTES",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PPG],
    },
    CommandInfo {
        name: "UNITS_YEARS_OR_PERIODS",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PPG],
    },
    CommandInfo {
        name: "UNITS_YEARS_OR_MINUTES",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(0),
        parameters: &[PPG],
    },
    // cargo amounts
    CommandInfo {
        name: "CARGO_LONG",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(1),
        parameters: &[P_G, PP_],
    },
    CommandInfo {
        name: "CARGO_SHORT",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(1),
        parameters: &[P_G, PP_],
    },
    CommandInfo {
        name: "CARGO_TINY",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: Some(1),
        parameters: &[P__, PP_],
    },
    // dates
    CommandInfo {
        name: "DATE1920_LONG",
        norm_name: None,
        dialects: DN__,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P__],
    },
    CommandInfo {
        name: "DATE1920_SHORT",
        norm_name: None,
        dialects: DN__,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P__],
    },
    CommandInfo {
        name: "DATE_LONG",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P__],
    },
    CommandInfo {
        name: "DATE_SHORT",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P__],
    },
    CommandInfo {
        name: "DATE_TINY",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P__],
    },
    CommandInfo {
        name: "DATE_ISO",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P__],
    },
    // names
    CommandInfo {
        name: "CARGO_NAME",
        norm_name: None,
        dialects: DN__,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
    CommandInfo {
        name: "CARGO_LIST",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P__],
    },
    CommandInfo {
        name: "INDUSTRY",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: true,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
    CommandInfo {
        name: "WAYPOINT",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
    CommandInfo {
        name: "STATION",
        norm_name: None,
        dialects: DNGO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
    CommandInfo {
        name: "DEPOT",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P_G, P__],
    },
    CommandInfo {
        name: "TOWN",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
    CommandInfo {
        name: "GROUP",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
    CommandInfo {
        name: "SIGN",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
    CommandInfo {
        name: "ENGINE",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
    CommandInfo {
        name: "VEHICLE",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
    CommandInfo {
        name: "COMPANY",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
    CommandInfo {
        name: "COMPANY_NUM",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P__],
    },
    CommandInfo {
        name: "PRESIDENT_NAME",
        norm_name: None,
        dialects: D_GO,
        occurence: Occurence::EXACT,
        front_only: false,
        allow_case: false,
        def_plural_subindex: None,
        parameters: &[P_G],
    },
];
